# Automatically generated by configure - do not modify
SRC_PATH=/home/spoorti/vmrevive/qemu/qemu-2.9.0-disable-rate-limit/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
